### ISSUE TITLE
Differences between CipSoft’s `10.90-map.png` and our maps

### ISSUE THREAD

**Issue by mathiasbynens** [tibiamaps/tibia-map-data#14]
[CipSoft’s map image](https://github.com/tibiamaps/tibia-map-data/files/181335/cipsoft-10.90-map.png.tar.gz) (that they sent to supported fansites before the 10.90 update) is not 100% accurate:

* It seems they replaced *every* black pixel with blue, even in areas that are supposed to be black like <https://tibiamaps.github.io/tibia-map/#33177,31267,7:3>.
* Their map excludes several mini world change-only areas. (Our maps contain as many of those as possible as long as they appear in places that are empty/water otherwise.)
* Missing area: [Realm of Dreams](http://tibia.wikia.com/wiki/Realm_of_Dreams): https://tibiamaps.github.io/tibia-map/#32821,31504,7:1
* Missing Sea serpent area: https://tibiamaps.github.io/tibia-map/#31942,31045,7:2

So, some differences are expected/intended. 

However, the following differences need to be looked into. Things that are on CipSoft’s map but not on ours:

#### Areas that require manual exploration (as we need proper pathfinding data)

- [x] teleport to Fazzrah around this area: https://tibiamaps.github.io/tibia-map/#33309,31181,7:2

#### Unreachable areas (i.e. pathfinding data doesn’t matter) that should be added manually

- [x] this island should be bigger: https://tibiamaps.github.io/tibia-map/#33361,31146,7:2
- [x] this rock should be bigger: https://tibiamaps.github.io/tibia-map/#33318,31258,7:1
- [x] this rock should be bigger: https://tibiamaps.github.io/tibia-map/#33332,31366,7:1
- [x] this rock should be bigger: https://tibiamaps.github.io/tibia-map/#32598,31388,7:1
- [x] this rock should be bigger: https://tibiamaps.github.io/tibia-map/#32054,31856,7:1
- [x] this island should be bigger: https://tibiamaps.github.io/tibia-map/#33381,31464,7:1
- [x] this island should be bigger: https://tibiamaps.github.io/tibia-map/#32639,32377,7:2
- [x] this rock should be bigger: https://tibiamaps.github.io/tibia-map/#33499,32464,7:1
- [x] this rock should be bigger: https://tibiamaps.github.io/tibia-map/#33728,32411,7:1

**Comment by Sixish** [comment]
1. This is the teleport for the lizard boss, moved from Razachai. The Razachai boat will also need to be remapped to remove the yellow pixel.
2. I don't think you can reach that island.

**Comment by mathiasbynens** [comment]
Re: point 2, many rocks and other “edges” in CipSoft’s map are unreachable but we can add them anyway. If anyone knows how far those rocks reach, it’s them! :)

**Comment by mathiasbynens** [comment]
Issue updated. @Sixish Would you mind going over the “areas missing from CipSoft’s map” section and seeing if you recognize anything? Thanks!

**Comment by Sixish** [comment]
Areas missing from CipSoft’s map:
1. Realm of Dreams, see tunnels below ground.
2. Sea serpent area, just look below.

**Comment by mathiasbynens** [comment]
Thanks so much! I’ll update the post at the top with that info.
