### ISSUE TITLE
Some Random Issues

### ISSUE THREAD

**Issue by Hunter-of-Dragoes** [tibiamaps/tibia-map-data#51]
These are some issues I noticed on the map while playing the game. Some are duplicated areas (due to the merge we had with Odyssey's map), others are just wrongly assumed pixel color.

- [x] [This floor](https://tibiamaps.io/map#32681,31700,2:2) does not exist. (This can't be re-explored in game, files are _32512_31488_2_)
- [x] [This mountain floor](https://tibiamaps.io/map#33250,31769,3:2) as well as [this one](https://tibiamaps.io/map#33250,31769,4:2) do not exist. (Only partially re-explored in game)
[Minimap_Color_33024_31744_3.zip](https://github.com/tibiamaps/tibia-map-data/files/1715128/Minimap_Color_33024_31744_3.zip) 
[Minimap_Color_33024_31744_4.zip](https://github.com/tibiamaps/tibia-map-data/files/1715130/Minimap_Color_33024_31744_4.zip)
- [x] [These grey pixels](https://tibiamaps.io/map#33220,31752,4:2) do not exist. (Same file as above)
- [x] [These grey pixels](https://tibiamaps.io/map#31988,32853,4:2) do not exist too. (Fully re-explored)
[Minimap_Color_31744_32768_4.zip](https://github.com/tibiamaps/tibia-map-data/files/1715140/Minimap_Color_31744_32768_4.zip)
- [x] [These green pixels](https://tibiamaps.io/map#32015,32835,4:2) are actually **grey**. (Only partially re-explored in game)
[Minimap_Color_32000_32768_4.zip](https://github.com/tibiamaps/tibia-map-data/files/1715143/Minimap_Color_32000_32768_4.zip)
